version: '3.1'

services:

  db:
    image: mariadb:11.3
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ./.dbdata:/var/lib/mysql:Z

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080