web_server:
    port: 8081
    timeout: 10
telegram:
    token: '<secdist>'
    use_webhook: false
    limit: 1
    timeout: 60
    allowed_chats_id:
        - 70250337
mysql:
    host: '<secdist>'
    user: '<secdist>'
    password: '<secdist>'
    port: 0
    database: '<secdist>'
    sslmode: disable
    max_open_connections: 5
    max_idle_connections: 2
    limit: 10
rss_reader:
    timeout: 3
    buffer_size: 10
    posts_settings:
        new_feeds:
            days_in_past: 7
            at_least_once_post: true