web_server:
    port: 8081
    timeout: 10
telegram:
    token: '<secdist>'
    limit: 1
    timeout: 60
    allowed_chats_id:
        - -1001549464996
mysql:
    host: '<secdist>'
    user: '<secdist>'
    password: '<secdist>'
    port: 0
    database: '<secdist>'
    sslmode: disable
    max_open_connections: 5
    max_idle_connections: 2
    limit: 10
rss_reader:
    timeout: 3