openapi: 3.10.0
info:
  title: FeedsGram
  description: FeedsGram API
  version: 1.0.0

paths:
  /v1/system/status:
    get:
      description: |
        Получение информации о состоянии системы
      operationId: GetSystemStatus
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemStatus'

  /ping:
    get:
      description: |
        Ручка статуса системы
      operationId: GetPing
      responses:
        200:
          description: OK
        500:
          description: has some troubles


components:
  schemas:
    Error:
      type: object
      description: Ошибка
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Машиночитаемый код ошибки
        message:
          type: string
    
    SystemStatus:
      type: object
      description: Информация о системе
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - ok
            - warn
            - crit
