openapi: 3.10.0
info:
  title: FeedsGram
  description: FeedsGram API
  version: 1.0.0

paths:
  /v1/notes/list:
    get:
      description: |
        Получение списка заметок
      operationId: GetNotesList
      parameters:
        - $ref: '#/components/schemas/Cursor'
        - $ref: '#/components/schemas/Limit'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotesList'


components:
  schemas:
    Cursor:
      in: query
      name: limit
      description: Курсор (NoteId) от которого начинать поиск
      required: false
      schema:
        type: string